//
// Basics
//

#define grey(g)              g g g
#define black                grey(0.0)
#define white                grey(1)

#define red                  #FF0000
#define green                0 1 0
#define blue                 0 0 1
#define cyan                 0 1 1
#define yellow               1 1 0
#define magenta              1 0 1
#define hc_blue              #ffffff

#define pink                 1 0.8 0.8
#define mint                 0.8 1 0.8
#define light_blue           0.5 0.5 1
#define light_yellow         1 1 0.5
#define orange               1 0.5 0
#define brown                #8C6238

//
// New variables
//

#define bg_high              #1E2221
#define bg_medium            #262626
#define bg_low               #1E1E1F
#define bg_graph             #1E2221

#define selection            #bbbbff
#define border               #609090
#define disabled             grey(0.2)

#define button               #404040

#define bevel_high           grey(0.52)
#define bevel_low            black

#define separator            #363738
#define error                1 0 0

#define text                 #ACDAD5
#define text_dim             grey(0.5)

//
// Old variables
//

#define dark_base            grey(0.179) // Textbox line number bg
#define dark_grad_high       grey(0.1)
#define dark_grad_low        #1F1F1F
#define well                 grey(0.15)
#define list_a               DRKBASE
#define list_b               DRKGRADLOW
#define toolbar              #1A0F00

#define unknown              1 0 1

#define dark                 grey(0.2)
#define arrow                grey(0.5)

#define shadow1_5            grey(0.699)
#define shadow2              grey(0.63)
#define shadow3              grey(0.58)

#define pressed_high         #4A5E73
#define pressed_low          #768EA7

#define selection_base       #FF9600
#define selection_highlight2 1 0.9 0.5
#define slection_shadow      1 0.4 0

#define button_selection     selection_base
#define button_press         selection_base
#define base_alt             grey(0.151) // effect in spreadsheet

#define empty                dark_base

#define text_highlight       grey(0.9)

#define edit_bg              grey(0.075) // Textbox bg
#define edit_bg_highlight    grey(0.18)  // Textbox border
#define edit_bg_outline      grey(0.14)  // Textbox border
